ALTER TABLE users ADD COLUMN last_check_in_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN last_passive_signal_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN nudge_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN second_nudge_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE users ADD COLUMN family_notified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN family_notified_strong BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN urgent_overnight_alerts BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN timezone VARCHAR(64);